version: "2"
services:
  syslog:
    container_name: syslog
    build:
      context: .
    volumes:
      - /tmp/rsyslog-dev:/var/run/rsyslog/dev

  logging-app:
    build: "example-logging-app"
    ports:
      - "8088:80"
    links:
      # make sure syslog container starts up before the app
      - syslog
    volumes:
      - /tmp/rsyslog-dev/log:/dev/log

# vim: tabstop=2 shiftwidth=2 expandtab:
